config/routes.rb
Songnotes::Application.routes.draw do

  devise_for :admin_users

  root to: 'pages#home'

  match '/songs/149-johnny-cash-i-walk-the-line', :to => redirect('http://playsongnotes.com/songs/johnny-cash-i-walk-the-line/', status: 301)
  match '/songs/65-bryan-adams-summer-of-69', :to => redirect('http://playsongnotes.com/songs/bryan-adams-summer-of-69/', status: 301)
  match '/songs/70-neil-young-out-on-the-weekend', :to => redirect('http://playsongnotes.com/songs/neil-young-out-on-the-weekend/', status: 301)
  match '/songs/56-the-eagles-hotel-california', :to => redirect('http://playsongnotes.com/songs/eagles-hotel-california/', status: 301)
  match '/songs/126-ricky-nelson-lonesome-town', :to => redirect('http://playsongnotes.com/songs/ricky-nelson-lonesome-town/', status: 301)
  match '/songs/133-lynyrd-skynyrd-sweet-home-alabama', :to => redirect('http://playsongnotes.com/songs/lynyrd-skynyrd-sweet-home-alabama/', status: 301)
  match '/songs/108-johnny-cash-folsom-prison-blues', :to => redirect('http://playsongnotes.com/songs/johnny-cash-folsom-prison-blues/', status: 301)
  match '/songs/176-johnny-cash-give-my-love-to-rose', :to => redirect('http://playsongnotes.com/songs/johnny-cash-give-my-love-to-rose/', status: 301)
  match '/songs/163-frozen-jonathan-groff-reindeers-are-better-than-people', :to => redirect('http://playsongnotes.com/songs/frozen-reindeers-are-better-than-people/', status: 301)
  match '/songs/155-neil-diamond-sweet-caroline', :to => redirect('http://playsongnotes.com/songs/neil-diamond-sweet-caroline/', status: 301)
  match '/songs/154-daniel-johnston-true-love-will-find-you-in-the-end', :to => redirect('http://playsongnotes.com/songs/daniel-johnston-true-love-will-find-you-in-the-end/', status: 301)
  match '/songs/153-frozen-demi-lovato-let-it-go', :to => redirect('http://playsongnotes.com/songs/frozen-let-it-go/', status: 301)
  match '/songs/152-lorde-team', :to => redirect('http://playsongnotes.com/songs/lorde-team/', status: 301)
  match '/songs/151-leonard-cohen-hallelujah', :to => redirect('http://playsongnotes.com/songs/leonard-cohen-hallelujah/', status: 301)
  match '/songs/90-sublime-rivers-of-babylon', :to => redirect('http://playsongnotes.com/songs/sublime-rivers-of-babylon/', status: 301)
  match '/songs/150-old-crow-medicine-show-wagon-wheel', :to => redirect('http://playsongnotes.com/songs/old-crow-medicine-show-wagon-wheel/', status: 301)
  match '/songs/67-bob-marley-redemption-song', :to => redirect('http://playsongnotes.com/songs/bob-marley-redemption-song/', status: 301)
  match '/songs/105-of-monsters-and-men-little-talks', :to => redirect('http://playsongnotes.com/songs/of-monsters-and-men-little-talks/', status: 301)
  match '/songs/141-lorde-royals', :to => redirect('http://playsongnotes.com/songs/lorde-royals/', status: 301)
  match '/songs/148-alt-j-breezeblocks', :to => redirect('http://playsongnotes.com/songs/alt-j-breezeblocks/', status: 301)
  match '/songs/143-eddie-vedder-tonight-you-belong-to-me', :to => redirect('http://playsongnotes.com/songs/eddie-vedder-tonight-you-belong-with-me/', status: 301)
  match '/songs/145-dead-mans-bones-paper-ships', :to => redirect('http://playsongnotes.com/songs/dead-mans-bones-paper-ships/', status: 301)
  match '/songs/147-alt-j-matilda', :to => redirect('http://playsongnotes.com/songs/alt-j-matilda/', status: 301)
  match '/songs/107-jason-mraz-i-wont-give-up', :to => redirect('http://playsongnotes.com/songs/jason-mraz-i-wont-give-up/', status: 301)
  match '/songs/159-israel-kamakawiwoole-somewhere-over-the-rainbow-what-a-wonderful-world', :to => redirect('http://playsongnotes.com/songs/israel-kamakawiwoole-somewhere-over-the-rainbow-what-a-wonderful-world/', status: 301)
  match '/songs/168-toto-africa', :to => redirect('http://playsongnotes.com/songs/toto-africa/', status: 301)
  match '/songs/44-taylor-swift-you-belong-with-me', :to => redirect('http://playsongnotes.com/songs/taylor-swift-you-belong-with-me/', status: 301)
  match '/songs/61-taylor-swift-love-story', :to => redirect('http://playsongnotes.com/songs/taylor-swift-love-story/', status: 301)
  match '/songs/128-the-kinks-lola', :to => redirect('http://playsongnotes.com/songs/kinks-lola/', status: 301)

  namespace :admin do
    match '/' => "songs#index"
    resources :songs, :except => :show
    resources :artists, :except => :show
    resources :albums, :except => :show
  end

  match 'home' => 'pages#home', :as => 'home'
  match 'api' => 'pages#api', :as => 'api'

  resources :songs, :only => [:index, :show]
  resources :artists, :only => [:index, :show]
  resources :albums, :only => [:index, :show]

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :artist_id, :image_url, :label, :name, :url_rdio, :url_wikipedia, :year
  belongs_to :artist
  has_many :songs
end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < Admin::BaseController
  before_filter :prepare_songs, :except => :index
  before_filter :prepare_artists, :except => :index

  def index
    @albums = Album.order(sort_column + ' ' + sort_direction)
  end

  def new
    @album = Album.new
  end

  def edit
    @album = Album.find(params[:id])
  end

  def create
    @album = Album.new(params[:album])
    if @album.save
      redirect_to admin_albums_url, notice: "Successfully created album."
    else
      render :new
    end
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(params[:album])
      redirect_to admin_albums_url, notice: "Successfully updated album."    
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    respond_to do |format|
      format.html { redirect_to admin_albums_url, notice: "Successfully deleted album." }
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    params[:sort] || "name"
  end
  helper_method :sort_column

  def sort_direction
    params[:direction] || "asc"
  end
  helper_method :sort_direction
  
  def prepare_songs
    @albums = Song.find(:all, :order => "LOWER(title)")
  end

  def prepare_artists
    @artists = Artist.find(:all, :order => "LOWER(name)")
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :prepare_artists

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to albums_url, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  private
  
  def prepare_artists
    @artists = Artist.all
  end
  
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/admin/albums/_form.html.erb
<%= form_for [:admin, @album] do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Artist" %><br />
    <%= f.collection_select(:artist_id, @artists, :id, :name, :include_blank => "")%>
  </div>
  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :url_wikipedia %><br />
    <%= f.text_field :url_wikipedia %>
  </div>
  <div class="field">
    <%= f.label :url_rdio %><br />
    <%= f.text_field :url_rdio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/admin/albums/index.html.erb
<div class="admin">

    <% unless notice.blank? %>
      <p style="background:yellow; padding: 12px 15px;"><%= notice %></p>
    <% end %>

    <h1>Albums</h1>

    <p style="margin:20px 0"><%= link_to 'Add New Album', new_admin_album_path, :class => 'btn' %></p>

    <table>
      <tr>
        <th width="300">Name</th>
        <th>Artist</th>
        <th># Songs</th>
        <th>Label</th>
        <th>Year</th>
        <th>Image url</th>
        <th>Url wikipedia</th>
        <th>Url rdio</th>
        <th></th>
      </tr>

    <% @albums.each do |album| %>
      <tr>
        <td><%= link_to album.name, edit_admin_album_url(album) %></td>
        <td><%= album.artist.blank? ? "--" : album.artist.name %></td>
        <td><%= album.songs.count %></td>
        <td><%= album.label %></td>
        <td><%= album.year %></td>
        <td><%= album.image_url %></td>
        <td><%= album.url_wikipedia %></td>
        <td><%= album.url_rdio %></td>
        <td><%= link_to 'Destroy', [:admin, album], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>

    <br />

    <p style="margin:20px 0"><%= link_to 'Add New Album', new_admin_album_path, :class => 'btn' %></p>

</div>

app/views/admin/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_albums_path %>