config/routes.rb
Songnotes::Application.routes.draw do

  devise_for :admin_users

  root to: 'pages#home'

  match '/songs/149-johnny-cash-i-walk-the-line', :to => redirect('http://playsongnotes.com/songs/johnny-cash-i-walk-the-line/', status: 301)
  match '/songs/65-bryan-adams-summer-of-69', :to => redirect('http://playsongnotes.com/songs/bryan-adams-summer-of-69/', status: 301)
  match '/songs/70-neil-young-out-on-the-weekend', :to => redirect('http://playsongnotes.com/songs/neil-young-out-on-the-weekend/', status: 301)
  match '/songs/56-the-eagles-hotel-california', :to => redirect('http://playsongnotes.com/songs/eagles-hotel-california/', status: 301)
  match '/songs/126-ricky-nelson-lonesome-town', :to => redirect('http://playsongnotes.com/songs/ricky-nelson-lonesome-town/', status: 301)
  match '/songs/133-lynyrd-skynyrd-sweet-home-alabama', :to => redirect('http://playsongnotes.com/songs/lynyrd-skynyrd-sweet-home-alabama/', status: 301)
  match '/songs/108-johnny-cash-folsom-prison-blues', :to => redirect('http://playsongnotes.com/songs/johnny-cash-folsom-prison-blues/', status: 301)
  match '/songs/176-johnny-cash-give-my-love-to-rose', :to => redirect('http://playsongnotes.com/songs/johnny-cash-give-my-love-to-rose/', status: 301)
  match '/songs/163-frozen-jonathan-groff-reindeers-are-better-than-people', :to => redirect('http://playsongnotes.com/songs/frozen-reindeers-are-better-than-people/', status: 301)
  match '/songs/155-neil-diamond-sweet-caroline', :to => redirect('http://playsongnotes.com/songs/neil-diamond-sweet-caroline/', status: 301)
  match '/songs/154-daniel-johnston-true-love-will-find-you-in-the-end', :to => redirect('http://playsongnotes.com/songs/daniel-johnston-true-love-will-find-you-in-the-end/', status: 301)
  match '/songs/153-frozen-demi-lovato-let-it-go', :to => redirect('http://playsongnotes.com/songs/frozen-let-it-go/', status: 301)
  match '/songs/152-lorde-team', :to => redirect('http://playsongnotes.com/songs/lorde-team/', status: 301)
  match '/songs/151-leonard-cohen-hallelujah', :to => redirect('http://playsongnotes.com/songs/leonard-cohen-hallelujah/', status: 301)
  match '/songs/90-sublime-rivers-of-babylon', :to => redirect('http://playsongnotes.com/songs/sublime-rivers-of-babylon/', status: 301)
  match '/songs/150-old-crow-medicine-show-wagon-wheel', :to => redirect('http://playsongnotes.com/songs/old-crow-medicine-show-wagon-wheel/', status: 301)
  match '/songs/67-bob-marley-redemption-song', :to => redirect('http://playsongnotes.com/songs/bob-marley-redemption-song/', status: 301)
  match '/songs/105-of-monsters-and-men-little-talks', :to => redirect('http://playsongnotes.com/songs/of-monsters-and-men-little-talks/', status: 301)
  match '/songs/141-lorde-royals', :to => redirect('http://playsongnotes.com/songs/lorde-royals/', status: 301)
  match '/songs/148-alt-j-breezeblocks', :to => redirect('http://playsongnotes.com/songs/alt-j-breezeblocks/', status: 301)
  match '/songs/143-eddie-vedder-tonight-you-belong-to-me', :to => redirect('http://playsongnotes.com/songs/eddie-vedder-tonight-you-belong-with-me/', status: 301)
  match '/songs/145-dead-mans-bones-paper-ships', :to => redirect('http://playsongnotes.com/songs/dead-mans-bones-paper-ships/', status: 301)
  match '/songs/147-alt-j-matilda', :to => redirect('http://playsongnotes.com/songs/alt-j-matilda/', status: 301)
  match '/songs/107-jason-mraz-i-wont-give-up', :to => redirect('http://playsongnotes.com/songs/jason-mraz-i-wont-give-up/', status: 301)
  match '/songs/159-israel-kamakawiwoole-somewhere-over-the-rainbow-what-a-wonderful-world', :to => redirect('http://playsongnotes.com/songs/israel-kamakawiwoole-somewhere-over-the-rainbow-what-a-wonderful-world/', status: 301)
  match '/songs/168-toto-africa', :to => redirect('http://playsongnotes.com/songs/toto-africa/', status: 301)
  match '/songs/44-taylor-swift-you-belong-with-me', :to => redirect('http://playsongnotes.com/songs/taylor-swift-you-belong-with-me/', status: 301)
  match '/songs/61-taylor-swift-love-story', :to => redirect('http://playsongnotes.com/songs/taylor-swift-love-story/', status: 301)
  match '/songs/128-the-kinks-lola', :to => redirect('http://playsongnotes.com/songs/kinks-lola/', status: 301)

  namespace :admin do
    match '/' => "songs#index"
    resources :songs, :except => :show
    resources :artists, :except => :show
    resources :albums, :except => :show
  end

  match 'home' => 'pages#home', :as => 'home'
  match 'api' => 'pages#api', :as => 'api'

  resources :songs, :only => [:index, :show]
  resources :artists, :only => [:index, :show]
  resources :albums, :only => [:index, :show]

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :bio_long, :bio_short, :image_url, :name, :url_facebook, :url_rdio, :url_twitter, :url_website, :url_wikipedia, :url_youtube_official
  has_many :albums
  has_many :songs
end

app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < Admin::BaseController
  before_filter :prepare_songs, :except => :index
  before_filter :prepare_albums, :except => :index

  def index
    @artists = Artist.order(sort_column + ' ' + sort_direction)
  end

  def new
    @artist = Artist.new
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def create
    @artist = Artist.new(params[:artist])
    if @artist.save
      redirect_to admin_artists_url, notice: "Successfully created artist."
    else
      render :new
    end
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update_attributes(params[:artist])
      redirect_to admin_artists_url, notice: "Successfully updated artist."    
    else
      render :edit
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to admin_artists_url }
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    params[:sort] || "name"
  end
  helper_method :sort_column

  def sort_direction
    params[:direction] || "asc"
  end
  helper_method :sort_direction
  
  def prepare_songs
    @artists = Song.find(:all, :order => "LOWER(title)")
  end

  def prepare_albums
    @albums = Album.find(:all, :order => "LOWER(name)")
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  # GET /artists
  # GET /artists.json
  def index
    
    # The 'LOWER' text keeps Postgres from being case INsensitive. Via http://stackoverflow.com/questions/2983687/how-to-do-case-insensitive-order-in-rails-with-postgresql
    @artists = Artist.find(:all, :order => "LOWER(name)")
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.json
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(params[:artist])

    respond_to do |format|
      if @artist.save
        format.html { redirect_to artists_url, notice: 'Artist was successfully created.' }
        format.json { render json: @artist, status: :created, location: @artist }
      else
        format.html { render action: "new" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.json
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to artists_url, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio_short %><br />
    <%= f.text_area :bio_short %>
  </div>
  <div class="field">
    <%= f.label :bio_long %><br />
    <%= f.text_area :bio_long %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :url_website %><br />
    <%= f.text_field :url_website %>
  </div>
  <div class="field">
    <%= f.label :url_twitter %><br />
    <%= f.text_field :url_twitter %>
  </div>
  <div class="field">
    <%= f.label :url_facebook %><br />
    <%= f.text_field :url_facebook %>
  </div>
  <div class="field">
    <%= f.label :url_wikipedia %><br />
    <%= f.text_field :url_wikipedia %>
  </div>
  <div class="field">
    <%= f.label :url_youtube_official %><br />
    <%= f.text_field :url_youtube_official %>
  </div>
  <div class="field">
    <%= f.label :url_rdio %><br />
    <%= f.text_field :url_rdio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/index.html.erb
<%= render "shared/admin_nav" %>

<div class="admin">

  <% unless notice.blank? %>
    <p style="background:yellow; padding: 12px 15px;"><%= notice %></p>
  <% end %>

  <h1>Artists</h1>

  <p style="margin:20px 0"><%= link_to 'Add New Artist', new_artist_path, :class => 'btn' %></p>

  <table>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th># Albums</th>
      <th># Songs</th>
      <th>Bio short</th>
      <th>Bio long</th>
      <th>Image url</th>
      <th>Url website</th>
      <th>Url twitter</th>
      <th>Url facebook</th>
      <th>Url wikipedia</th>
      <th>Url youtube official</th>
      <th>Url rdio</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @artists.each do |artist| %>
    <tr>
      <td><%= artist.id %></td>
      <td><%= link_to artist.name, edit_artist_path(artist) %></td>
      <td><%= artist.albums.count %></td>
      <td><%= artist.songs.count %></td>
      <td><%= artist.bio_short %></td>
      <td><%= artist.bio_long %></td>
      <td><%= artist.image_url %></td>
      <td><%= artist.url_website %></td>
      <td><%= artist.url_twitter %></td>
      <td><%= artist.url_facebook %></td>
      <td><%= artist.url_wikipedia %></td>
      <td><%= artist.url_youtube_official %></td>
      <td><%= artist.url_rdio %></td>
      <td><%= link_to 'Show', artist %></td>
      <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
      <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>

</div>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @artist.name %>
</p>

<p>
  <b>Bio short:</b>
  <%= @artist.bio_short %>
</p>

<p>
  <b>Bio long:</b>
  <%= @artist.bio_long %>
</p>

<p>
  <b>Image url:</b>
  <%= @artist.image_url %>
</p>

<p>
  <b>Url website:</b>
  <%= @artist.url_website %>
</p>

<p>
  <b>Url twitter:</b>
  <%= @artist.url_twitter %>
</p>

<p>
  <b>Url facebook:</b>
  <%= @artist.url_facebook %>
</p>

<p>
  <b>Url wikipedia:</b>
  <%= @artist.url_wikipedia %>
</p>

<p>
  <b>Url youtube official:</b>
  <%= @artist.url_youtube_official %>
</p>

<p>
  <b>Url rdio:</b>
  <%= @artist.url_rdio %>
</p>


<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>