config/routes.rb
Songnotes::Application.routes.draw do

  devise_for :admin_users

  root to: 'pages#home'

  match '/songs/149-johnny-cash-i-walk-the-line', :to => redirect('http://playsongnotes.com/songs/johnny-cash-i-walk-the-line/', status: 301)
  match '/songs/65-bryan-adams-summer-of-69', :to => redirect('http://playsongnotes.com/songs/bryan-adams-summer-of-69/', status: 301)
  match '/songs/70-neil-young-out-on-the-weekend', :to => redirect('http://playsongnotes.com/songs/neil-young-out-on-the-weekend/', status: 301)
  match '/songs/56-the-eagles-hotel-california', :to => redirect('http://playsongnotes.com/songs/eagles-hotel-california/', status: 301)
  match '/songs/126-ricky-nelson-lonesome-town', :to => redirect('http://playsongnotes.com/songs/ricky-nelson-lonesome-town/', status: 301)
  match '/songs/133-lynyrd-skynyrd-sweet-home-alabama', :to => redirect('http://playsongnotes.com/songs/lynyrd-skynyrd-sweet-home-alabama/', status: 301)
  match '/songs/108-johnny-cash-folsom-prison-blues', :to => redirect('http://playsongnotes.com/songs/johnny-cash-folsom-prison-blues/', status: 301)
  match '/songs/176-johnny-cash-give-my-love-to-rose', :to => redirect('http://playsongnotes.com/songs/johnny-cash-give-my-love-to-rose/', status: 301)
  match '/songs/163-frozen-jonathan-groff-reindeers-are-better-than-people', :to => redirect('http://playsongnotes.com/songs/frozen-reindeers-are-better-than-people/', status: 301)
  match '/songs/155-neil-diamond-sweet-caroline', :to => redirect('http://playsongnotes.com/songs/neil-diamond-sweet-caroline/', status: 301)
  match '/songs/154-daniel-johnston-true-love-will-find-you-in-the-end', :to => redirect('http://playsongnotes.com/songs/daniel-johnston-true-love-will-find-you-in-the-end/', status: 301)
  match '/songs/153-frozen-demi-lovato-let-it-go', :to => redirect('http://playsongnotes.com/songs/frozen-let-it-go/', status: 301)
  match '/songs/152-lorde-team', :to => redirect('http://playsongnotes.com/songs/lorde-team/', status: 301)
  match '/songs/151-leonard-cohen-hallelujah', :to => redirect('http://playsongnotes.com/songs/leonard-cohen-hallelujah/', status: 301)
  match '/songs/90-sublime-rivers-of-babylon', :to => redirect('http://playsongnotes.com/songs/sublime-rivers-of-babylon/', status: 301)
  match '/songs/150-old-crow-medicine-show-wagon-wheel', :to => redirect('http://playsongnotes.com/songs/old-crow-medicine-show-wagon-wheel/', status: 301)
  match '/songs/67-bob-marley-redemption-song', :to => redirect('http://playsongnotes.com/songs/bob-marley-redemption-song/', status: 301)
  match '/songs/105-of-monsters-and-men-little-talks', :to => redirect('http://playsongnotes.com/songs/of-monsters-and-men-little-talks/', status: 301)
  match '/songs/141-lorde-royals', :to => redirect('http://playsongnotes.com/songs/lorde-royals/', status: 301)
  match '/songs/148-alt-j-breezeblocks', :to => redirect('http://playsongnotes.com/songs/alt-j-breezeblocks/', status: 301)
  match '/songs/143-eddie-vedder-tonight-you-belong-to-me', :to => redirect('http://playsongnotes.com/songs/eddie-vedder-tonight-you-belong-with-me/', status: 301)
  match '/songs/145-dead-mans-bones-paper-ships', :to => redirect('http://playsongnotes.com/songs/dead-mans-bones-paper-ships/', status: 301)
  match '/songs/147-alt-j-matilda', :to => redirect('http://playsongnotes.com/songs/alt-j-matilda/', status: 301)
  match '/songs/107-jason-mraz-i-wont-give-up', :to => redirect('http://playsongnotes.com/songs/jason-mraz-i-wont-give-up/', status: 301)
  match '/songs/159-israel-kamakawiwoole-somewhere-over-the-rainbow-what-a-wonderful-world', :to => redirect('http://playsongnotes.com/songs/israel-kamakawiwoole-somewhere-over-the-rainbow-what-a-wonderful-world/', status: 301)
  match '/songs/168-toto-africa', :to => redirect('http://playsongnotes.com/songs/toto-africa/', status: 301)
  match '/songs/44-taylor-swift-you-belong-with-me', :to => redirect('http://playsongnotes.com/songs/taylor-swift-you-belong-with-me/', status: 301)
  match '/songs/61-taylor-swift-love-story', :to => redirect('http://playsongnotes.com/songs/taylor-swift-love-story/', status: 301)
  match '/songs/128-the-kinks-lola', :to => redirect('http://playsongnotes.com/songs/kinks-lola/', status: 301)

  namespace :admin do
    match '/' => "songs#index"
    resources :songs, :except => :show
    resources :artists, :except => :show
    resources :albums, :except => :show
  end

  match 'home' => 'pages#home', :as => 'home'
  match 'api' => 'pages#api', :as => 'api'

  resources :songs, :only => [:index, :show]
  resources :artists, :only => [:index, :show]
  resources :albums, :only => [:index, :show]

end

app/views/shared/_admin_nav.html.erb
<div class="" style="background: #333; padding: 12px;">
  <p style="margin: 0;color:#fff;padding: 0;font-size: 16px;line-height: 24px;">
    <%= link_to "Artists", admin_artists_url, :style=>"color:#ffff00;" %>&nbsp;&nbsp;|&nbsp;
    <%= link_to "Albums", admin_albums_url, :style=>"color:#ffff00;" %>&nbsp;&nbsp;|&nbsp;
    <%= link_to "Songs", admin_songs_url, :style=>"color:#ffff00;" %>
  </p>
</div>

app/views/shared/_nav.html.erb
    <div id="shelf">
      <div id="title">
        <a class="title-link-wrap" href="/">
          <img src="/assets/logo.svg" />
          <div class="text">
            <h1>Songnotes</h1>
            <p>the hand-crafted music library of @davidpots</p>
          </div> <!-- end: .text -->
        </a>
        <a id="navburger" href="#">&nbsp;</a>
      </div> <!-- #title -->

      <div id="drawer">
        <div id="nav">
          <ul>
            <li><a href="<%= root_url %>#video_lessons">Video Lessons</a></li>
            <li><a href="<%= root_url %>#browse_all_songs">browse all songs</a></li>
            <li><a href="<%= root_url %>#tipjar">tip jar</a></li>
          </ul>
        </div> <!-- end: #nav -->

        <div id="social">
          <p>follow Songnotes:</p>
          <ul>
            <li class="tw"><a href="http://twitter.com/playsongnotes">twitter</a></li>
            <li class="fb"><a href="http://facebook.com/songnotes">facebook</a></li>
            <li class="yt"><a href="http://www.youtube.com/user/playsongnotes">youtube</a></li>
            <li class="gplus"><a href="https://plus.google.com/+songnotesCC" rel="publisher">google+</a></li>
          </ul>
        </div> <!-- end: #nav -->
      </div> <!-- end: #drawer -->

    </div> <!-- end: #shelf -->